[tool.poetry]
name = "visualizer"
version = "0.1.0"
description = "A universal visualization tool for spectral sequences of all kinds"
authors = ["Joey Beauvais-Feisthauer <joeybf@wayne.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
